A-658 Merge PartialCodec and Codec into a single 'Codec' entity
input-output-hk/decco pull request #15
Opened 2019-04-09 11:03 UTC by marcesquerra

2019-04-09 13:15 UTC, jtownson requested changes

2019-04-09 13:15 UTC, jtownson commented on src/io/iohk/decco/BufferInstantiatior.scala
> +package io.iohk.decco
Typo in filename (too many 'i's).

2019-04-09 14:05 UTC, marcesquerra commented on src/io/iohk/decco/BufferInstantiatior.scala
> +package io.iohk.decco
Good catch, thanks!

Fixed :)

2019-04-10 01:36 UTC, AlexITC approved these changes
Now we just need another refactor that uses a backwards-compatibility protocol, like protobuf.

2019-04-10 01:36 UTC, AlexITC commented on src/io/iohk/decco/Codec.scala
> +      self.decodeImpl(start, source) match {
Looks like we can use for-comprehension.

2019-04-10 01:36 UTC, AlexITC commented on src/io/iohk/decco/Codec.scala
> +          t2u(t) match {
an alternative: `t2u(t).map { u => Right(DecodeResult(u, nextIndex)) }.toRight(Failure)`

2019-04-10 01:36 UTC, AlexITC commented on src/io/iohk/decco/Codec.scala
> +  def apply[T](implicit ev: Codec[T]): Codec[T] = ev
nice trick

2019-04-12 14:07 UTC, merged